# Generated by Django 3.1.1 on 2020-11-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
