# Generated by Django 3.1.1 on 2020-11-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201123_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': '验证码表', 'verbose_name_plural': '验证码表'},
        ),
    ]
