# Generated by Django 3.1.1 on 2020-11-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_auto_20201122_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_last_time',
            field=models.DateField(auto_now=True, verbose_name='最新编辑时间'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_title',
            field=models.CharField(blank=True, default='未命名', max_length=50, verbose_name='标题'),
        ),
    ]
